'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NuevaVisitaCteCaseta
    
    '''<summary>
    '''lbl_nombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nombre As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''cmBoxProyecto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmBoxProyecto As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''cmBoxModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmBoxModelo As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''txBoxEsquemaFinanciero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBoxEsquemaFinanciero As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txBoxMedio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBoxMedio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txBoxCual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBoxCual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dtFechaVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtFechaVisita As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''txBoxUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBoxUsuario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txBoxAsesor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBoxAsesor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dtp_finicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtp_finicio As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''dtp_ffinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtp_ffinal As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''txBoxTipoCamapana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txBoxTipoCamapana As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmBoxClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmBoxClasificacion As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''cmBoxMotivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmBoxMotivo As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''cmBoxSubMotivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmBoxSubMotivo As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''cmBoxTipoVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmBoxTipoVisita As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''btnAsignaVisita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAsignaVisita As Global.DevExpress.Web.ASPxButton
    
    '''<summary>
    '''grdViewVisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdViewVisitas As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''lbl_mensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_mensaje As Global.System.Web.UI.WebControls.Literal
End Class
