'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EKREST
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OrigenAgente", [Namespace]:="http://schemas.datacontract.org/2004/07/WCF_ENKONTROL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OrigenAgente
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrigenField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Origen() As String
            Get
                Return Me.OrigenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OrigenField, value) <> true) Then
                    Me.OrigenField = value
                    Me.RaisePropertyChanged("Origen")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Prospeccion", [Namespace]:="http://schemas.datacontract.org/2004/07/WCF_ENKONTROL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Prospeccion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private agenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ccField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private clienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private empresaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreLiderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroAgenteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroClienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroLiderField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private zonaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property agente() As String
            Get
                Return Me.agenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.agenteField, value) <> true) Then
                    Me.agenteField = value
                    Me.RaisePropertyChanged("agente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cc() As String
            Get
                Return Me.ccField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ccField, value) <> true) Then
                    Me.ccField = value
                    Me.RaisePropertyChanged("cc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cliente() As String
            Get
                Return Me.clienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.clienteField, value) <> true) Then
                    Me.clienteField = value
                    Me.RaisePropertyChanged("cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property empresa() As Integer
            Get
                Return Me.empresaField
            End Get
            Set
                If (Me.empresaField.Equals(value) <> true) Then
                    Me.empresaField = value
                    Me.RaisePropertyChanged("empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombreLider() As String
            Get
                Return Me.nombreLiderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreLiderField, value) <> true) Then
                    Me.nombreLiderField = value
                    Me.RaisePropertyChanged("nombreLider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroAgente() As Integer
            Get
                Return Me.numeroAgenteField
            End Get
            Set
                If (Me.numeroAgenteField.Equals(value) <> true) Then
                    Me.numeroAgenteField = value
                    Me.RaisePropertyChanged("numeroAgente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCliente() As Integer
            Get
                Return Me.numeroClienteField
            End Get
            Set
                If (Me.numeroClienteField.Equals(value) <> true) Then
                    Me.numeroClienteField = value
                    Me.RaisePropertyChanged("numeroCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroLider() As Integer
            Get
                Return Me.numeroLiderField
            End Get
            Set
                If (Me.numeroLiderField.Equals(value) <> true) Then
                    Me.numeroLiderField = value
                    Me.RaisePropertyChanged("numeroLider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property zona() As String
            Get
                Return Me.zonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.zonaField, value) <> true) Then
                    Me.zonaField = value
                    Me.RaisePropertyChanged("zona")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Cancelacion", [Namespace]:="http://schemas.datacontract.org/2004/07/WCF_ENKONTROL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Cancelacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ccField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private empresaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fechaCancelacionField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreAgenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreClienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreLiderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroAgenteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroClienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroLiderField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private zonaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cc() As String
            Get
                Return Me.ccField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ccField, value) <> true) Then
                    Me.ccField = value
                    Me.RaisePropertyChanged("cc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property empresa() As String
            Get
                Return Me.empresaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.empresaField, value) <> true) Then
                    Me.empresaField = value
                    Me.RaisePropertyChanged("empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fechaCancelacion() As Date
            Get
                Return Me.fechaCancelacionField
            End Get
            Set
                If (Me.fechaCancelacionField.Equals(value) <> true) Then
                    Me.fechaCancelacionField = value
                    Me.RaisePropertyChanged("fechaCancelacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombreAgente() As String
            Get
                Return Me.nombreAgenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreAgenteField, value) <> true) Then
                    Me.nombreAgenteField = value
                    Me.RaisePropertyChanged("nombreAgente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombreCliente() As String
            Get
                Return Me.nombreClienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreClienteField, value) <> true) Then
                    Me.nombreClienteField = value
                    Me.RaisePropertyChanged("nombreCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombreLider() As String
            Get
                Return Me.nombreLiderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreLiderField, value) <> true) Then
                    Me.nombreLiderField = value
                    Me.RaisePropertyChanged("nombreLider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroAgente() As Integer
            Get
                Return Me.numeroAgenteField
            End Get
            Set
                If (Me.numeroAgenteField.Equals(value) <> true) Then
                    Me.numeroAgenteField = value
                    Me.RaisePropertyChanged("numeroAgente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCliente() As Integer
            Get
                Return Me.numeroClienteField
            End Get
            Set
                If (Me.numeroClienteField.Equals(value) <> true) Then
                    Me.numeroClienteField = value
                    Me.RaisePropertyChanged("numeroCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroLider() As Integer
            Get
                Return Me.numeroLiderField
            End Get
            Set
                If (Me.numeroLiderField.Equals(value) <> true) Then
                    Me.numeroLiderField = value
                    Me.RaisePropertyChanged("numeroLider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property zona() As String
            Get
                Return Me.zonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.zonaField, value) <> true) Then
                    Me.zonaField = value
                    Me.RaisePropertyChanged("zona")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Separacion", [Namespace]:="http://schemas.datacontract.org/2004/07/WCF_ENKONTROL"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Separacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private agenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ccField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private clienteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private empresaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreLiderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroAgenteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroClienteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private numeroLiderField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private zonaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property agente() As String
            Get
                Return Me.agenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.agenteField, value) <> true) Then
                    Me.agenteField = value
                    Me.RaisePropertyChanged("agente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cc() As String
            Get
                Return Me.ccField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ccField, value) <> true) Then
                    Me.ccField = value
                    Me.RaisePropertyChanged("cc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cliente() As String
            Get
                Return Me.clienteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.clienteField, value) <> true) Then
                    Me.clienteField = value
                    Me.RaisePropertyChanged("cliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property empresa() As Integer
            Get
                Return Me.empresaField
            End Get
            Set
                If (Me.empresaField.Equals(value) <> true) Then
                    Me.empresaField = value
                    Me.RaisePropertyChanged("empresa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombreLider() As String
            Get
                Return Me.nombreLiderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreLiderField, value) <> true) Then
                    Me.nombreLiderField = value
                    Me.RaisePropertyChanged("nombreLider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroAgente() As Integer
            Get
                Return Me.numeroAgenteField
            End Get
            Set
                If (Me.numeroAgenteField.Equals(value) <> true) Then
                    Me.numeroAgenteField = value
                    Me.RaisePropertyChanged("numeroAgente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroCliente() As Integer
            Get
                Return Me.numeroClienteField
            End Get
            Set
                If (Me.numeroClienteField.Equals(value) <> true) Then
                    Me.numeroClienteField = value
                    Me.RaisePropertyChanged("numeroCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property numeroLider() As Integer
            Get
                Return Me.numeroLiderField
            End Get
            Set
                If (Me.numeroLiderField.Equals(value) <> true) Then
                    Me.numeroLiderField = value
                    Me.RaisePropertyChanged("numeroLider")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property zona() As String
            Get
                Return Me.zonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.zonaField, value) <> true) Then
                    Me.zonaField = value
                    Me.RaisePropertyChanged("zona")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EKREST.Iwcf_enkontrol")>  _
    Public Interface Iwcf_enkontrol
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/DoWork", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/DoWork", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerConsultas", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerConsultasResponse")>  _
        Function ObtenerConsultas(ByVal Consulta As String, ByVal Numero_Empresa As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerConsultas", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerConsultasResponse")>  _
        Function ObtenerConsultasAsync(ByVal Consulta As String, ByVal Numero_Empresa As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_OrigenAgente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_OrigenAgenteResponse")>  _
        Function Obtener_OrigenAgente(ByVal Empleado As Integer) As EKREST.OrigenAgente()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_OrigenAgente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_OrigenAgenteResponse")>  _
        Function Obtener_OrigenAgenteAsync(ByVal Empleado As Integer) As System.Threading.Tasks.Task(Of EKREST.OrigenAgente())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentesResponse")>  _
        Function ObtenerAgentes() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentesResponse")>  _
        Function ObtenerAgentesAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_Prospectadores", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_ProspectadoresResponse")>  _
        Function ObtenerAgentes_Prospectadores() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_Prospectadores", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_ProspectadoresResponse")>  _
        Function ObtenerAgentes_ProspectadoresAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_Cerradores", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_CerradoresResponse")>  _
        Function ObtenerAgentes_Cerradores() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_Cerradores", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_CerradoresResponse")>  _
        Function ObtenerAgentes_CerradoresAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_Moviles", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_MovilesResponse")>  _
        Function ObtenerAgentes_Moviles() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_Moviles", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes_MovilesResponse")>  _
        Function ObtenerAgentes_MovilesAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_Agente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_AgenteResponse")>  _
        Function ObtenerDetalle_Agente(ByVal Numero_Empleado As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_Agente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_AgenteResponse")>  _
        Function ObtenerDetalle_AgenteAsync(ByVal Numero_Empleado As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_Estatus", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_EstatusResponse")>  _
        Function Actualizar_Agente_Estatus(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_Estatus", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_EstatusResponse")>  _
        Function Actualizar_Agente_EstatusAsync(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_ClienteResponse")>  _
        Function Obtener_Datos_Cliente(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_ClienteResponse")>  _
        Function Obtener_Datos_ClienteAsync(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente_X_LoteId", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente_X_LoteIdResponse")>  _
        Function Obtener_Datos_Cliente_X_LoteId(ByVal Empresa As Integer, ByVal Lote_Id As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente_X_LoteId", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente_X_LoteIdResponse")>  _
        Function Obtener_Datos_Cliente_X_LoteIdAsync(ByVal Empresa As Integer, ByVal Lote_Id As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_ClientesXEscriturar", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_ClientesXEscriturarResponse")>  _
        Function Obtener_ClientesXEscriturar() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_ClientesXEscriturar", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_ClientesXEscriturarResponse")>  _
        Function Obtener_ClientesXEscriturarAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerDatos_Empresa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerDatos_EmpresaResponse")>  _
        Function ObtenerDatos_Empresa(ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerDatos_Empresa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerDatos_EmpresaResponse")>  _
        Function ObtenerDatos_EmpresaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_Empresa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_EmpresaResponse")>  _
        Function ObtenerFraccionamientos_Empresa(ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_Empresa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_EmpresaResponse")>  _
        Function ObtenerFraccionamientos_EmpresaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Lotes", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_LotesResponse")>  _
        Function Obtener_Lotes(ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Lotes", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_LotesResponse")>  _
        Function Obtener_LotesAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Apartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Apartar_LoteResponse")>  _
        Function Apartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Apartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Apartar_LoteResponse")>  _
        Function Apartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Desapartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Desapartar_LoteResponse")>  _
        Function Desapartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Desapartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Desapartar_LoteResponse")>  _
        Function Desapartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerSManzanas", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerSManzanasResponse")>  _
        Function ObtenerSManzanas(ByVal Empresa As Integer, ByVal CC As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerSManzanas", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerSManzanasResponse")>  _
        Function ObtenerSManzanasAsync(ByVal Empresa As Integer, ByVal CC As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_TipoCasa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_TipoCasaResponse")>  _
        Function Obtener_TipoCasa(ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_TipoCasa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_TipoCasaResponse")>  _
        Function Obtener_TipoCasaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_IdLoteXCliente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_IdLoteXClienteResponse")>  _
        Function Obtener_IdLoteXCliente(ByVal Empresa As Integer, ByVal Cliente As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_IdLoteXCliente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_IdLoteXClienteResponse")>  _
        Function Obtener_IdLoteXClienteAsync(ByVal Empresa As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicacionesResponse")>  _
        Function ObtenerUbicaciones(ByVal Empresa As Integer, ByVal Centro_Costo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicacionesResponse")>  _
        Function ObtenerUbicacionesAsync(ByVal Empresa As Integer, ByVal Centro_Costo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratos", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratosResponse")>  _
        Function ObtenerContratos(ByVal LoteId As Integer, ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratos", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratosResponse")>  _
        Function ObtenerContratosAsync(ByVal LoteId As Integer, ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Prototipo", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_PrototipoResponse")>  _
        Function Obtener_Prototipo(ByVal Empresa As Integer, ByVal Centro_Costo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Prototipo", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_PrototipoResponse")>  _
        Function Obtener_PrototipoAsync(ByVal Empresa As Integer, ByVal Centro_Costo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_EntregaVivienda", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_EntregaViviendaResponse")>  _
        Function Obtener_EntregaVivienda(ByVal Empresa As Integer, ByVal Fec_Inico As Date, ByVal Fec_Fin As Date) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_EntregaVivienda", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_EntregaViviendaResponse")>  _
        Function Obtener_EntregaViviendaAsync(ByVal Empresa As Integer, ByVal Fec_Inico As Date, ByVal Fec_Fin As Date) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Prospecciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_ProspeccionesResponse")>  _
        Function Obtener_Prospecciones(ByVal FechaInicio As Date, ByVal FechaFin As Date) As EKREST.Prospeccion()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Prospecciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_ProspeccionesResponse")>  _
        Function Obtener_ProspeccionesAsync(ByVal FechaInicio As Date, ByVal FechaFin As Date) As System.Threading.Tasks.Task(Of EKREST.Prospeccion())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Cancelaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_CancelacionesResponse")>  _
        Function Obtener_Cancelaciones(ByVal FechaInicio As Date, ByVal FechaFin As Date) As EKREST.Cancelacion()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Cancelaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_CancelacionesResponse")>  _
        Function Obtener_CancelacionesAsync(ByVal FechaInicio As Date, ByVal FechaFin As Date) As System.Threading.Tasks.Task(Of EKREST.Cancelacion())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Separaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_SeparacionesResponse")>  _
        Function Obtener_Separaciones(ByVal FechaInicio As Date, ByVal FechaFin As Date) As EKREST.Separacion()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Separaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_SeparacionesResponse")>  _
        Function Obtener_SeparacionesAsync(ByVal FechaInicio As Date, ByVal FechaFin As Date) As System.Threading.Tasks.Task(Of EKREST.Separacion())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Iwcf_enkontrolChannel
        Inherits EKREST.Iwcf_enkontrol, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Iwcf_enkontrolClient
        Inherits System.ServiceModel.ClientBase(Of EKREST.Iwcf_enkontrol)
        Implements EKREST.Iwcf_enkontrol
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements EKREST.Iwcf_enkontrol.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements EKREST.Iwcf_enkontrol.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function ObtenerConsultas(ByVal Consulta As String, ByVal Numero_Empresa As Integer) As System.Data.DataTable Implements EKREST.Iwcf_enkontrol.ObtenerConsultas
            Return MyBase.Channel.ObtenerConsultas(Consulta, Numero_Empresa)
        End Function
        
        Public Function ObtenerConsultasAsync(ByVal Consulta As String, ByVal Numero_Empresa As Integer) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements EKREST.Iwcf_enkontrol.ObtenerConsultasAsync
            Return MyBase.Channel.ObtenerConsultasAsync(Consulta, Numero_Empresa)
        End Function
        
        Public Function Obtener_OrigenAgente(ByVal Empleado As Integer) As EKREST.OrigenAgente() Implements EKREST.Iwcf_enkontrol.Obtener_OrigenAgente
            Return MyBase.Channel.Obtener_OrigenAgente(Empleado)
        End Function
        
        Public Function Obtener_OrigenAgenteAsync(ByVal Empleado As Integer) As System.Threading.Tasks.Task(Of EKREST.OrigenAgente()) Implements EKREST.Iwcf_enkontrol.Obtener_OrigenAgenteAsync
            Return MyBase.Channel.Obtener_OrigenAgenteAsync(Empleado)
        End Function
        
        Public Function ObtenerAgentes() As String Implements EKREST.Iwcf_enkontrol.ObtenerAgentes
            Return MyBase.Channel.ObtenerAgentes
        End Function
        
        Public Function ObtenerAgentesAsync() As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerAgentesAsync
            Return MyBase.Channel.ObtenerAgentesAsync
        End Function
        
        Public Function ObtenerAgentes_Prospectadores() As String Implements EKREST.Iwcf_enkontrol.ObtenerAgentes_Prospectadores
            Return MyBase.Channel.ObtenerAgentes_Prospectadores
        End Function
        
        Public Function ObtenerAgentes_ProspectadoresAsync() As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerAgentes_ProspectadoresAsync
            Return MyBase.Channel.ObtenerAgentes_ProspectadoresAsync
        End Function
        
        Public Function ObtenerAgentes_Cerradores() As String Implements EKREST.Iwcf_enkontrol.ObtenerAgentes_Cerradores
            Return MyBase.Channel.ObtenerAgentes_Cerradores
        End Function
        
        Public Function ObtenerAgentes_CerradoresAsync() As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerAgentes_CerradoresAsync
            Return MyBase.Channel.ObtenerAgentes_CerradoresAsync
        End Function
        
        Public Function ObtenerAgentes_Moviles() As String Implements EKREST.Iwcf_enkontrol.ObtenerAgentes_Moviles
            Return MyBase.Channel.ObtenerAgentes_Moviles
        End Function
        
        Public Function ObtenerAgentes_MovilesAsync() As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerAgentes_MovilesAsync
            Return MyBase.Channel.ObtenerAgentes_MovilesAsync
        End Function
        
        Public Function ObtenerDetalle_Agente(ByVal Numero_Empleado As String) As String Implements EKREST.Iwcf_enkontrol.ObtenerDetalle_Agente
            Return MyBase.Channel.ObtenerDetalle_Agente(Numero_Empleado)
        End Function
        
        Public Function ObtenerDetalle_AgenteAsync(ByVal Numero_Empleado As String) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerDetalle_AgenteAsync
            Return MyBase.Channel.ObtenerDetalle_AgenteAsync(Numero_Empleado)
        End Function
        
        Public Function Actualizar_Agente_Estatus(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As Boolean Implements EKREST.Iwcf_enkontrol.Actualizar_Agente_Estatus
            Return MyBase.Channel.Actualizar_Agente_Estatus(Empresa, Empleado, Estatus)
        End Function
        
        Public Function Actualizar_Agente_EstatusAsync(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Actualizar_Agente_EstatusAsync
            Return MyBase.Channel.Actualizar_Agente_EstatusAsync(Empresa, Empleado, Estatus)
        End Function
        
        Public Function Obtener_Datos_Cliente(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As String Implements EKREST.Iwcf_enkontrol.Obtener_Datos_Cliente
            Return MyBase.Channel.Obtener_Datos_Cliente(Empresa, Numero_Cliente)
        End Function
        
        Public Function Obtener_Datos_ClienteAsync(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_Datos_ClienteAsync
            Return MyBase.Channel.Obtener_Datos_ClienteAsync(Empresa, Numero_Cliente)
        End Function
        
        Public Function Obtener_Datos_Cliente_X_LoteId(ByVal Empresa As Integer, ByVal Lote_Id As Integer) As String Implements EKREST.Iwcf_enkontrol.Obtener_Datos_Cliente_X_LoteId
            Return MyBase.Channel.Obtener_Datos_Cliente_X_LoteId(Empresa, Lote_Id)
        End Function
        
        Public Function Obtener_Datos_Cliente_X_LoteIdAsync(ByVal Empresa As Integer, ByVal Lote_Id As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_Datos_Cliente_X_LoteIdAsync
            Return MyBase.Channel.Obtener_Datos_Cliente_X_LoteIdAsync(Empresa, Lote_Id)
        End Function
        
        Public Function Obtener_ClientesXEscriturar() As String Implements EKREST.Iwcf_enkontrol.Obtener_ClientesXEscriturar
            Return MyBase.Channel.Obtener_ClientesXEscriturar
        End Function
        
        Public Function Obtener_ClientesXEscriturarAsync() As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_ClientesXEscriturarAsync
            Return MyBase.Channel.Obtener_ClientesXEscriturarAsync
        End Function
        
        Public Function ObtenerDatos_Empresa(ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.ObtenerDatos_Empresa
            Return MyBase.Channel.ObtenerDatos_Empresa(Empresa)
        End Function
        
        Public Function ObtenerDatos_EmpresaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerDatos_EmpresaAsync
            Return MyBase.Channel.ObtenerDatos_EmpresaAsync(Empresa)
        End Function
        
        Public Function ObtenerFraccionamientos_Empresa(ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.ObtenerFraccionamientos_Empresa
            Return MyBase.Channel.ObtenerFraccionamientos_Empresa(Empresa)
        End Function
        
        Public Function ObtenerFraccionamientos_EmpresaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerFraccionamientos_EmpresaAsync
            Return MyBase.Channel.ObtenerFraccionamientos_EmpresaAsync(Empresa)
        End Function
        
        Public Function Obtener_Lotes(ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.Obtener_Lotes
            Return MyBase.Channel.Obtener_Lotes(Empresa)
        End Function
        
        Public Function Obtener_LotesAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_LotesAsync
            Return MyBase.Channel.Obtener_LotesAsync(Empresa)
        End Function
        
        Public Function Apartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean Implements EKREST.Iwcf_enkontrol.Apartar_Lote
            Return MyBase.Channel.Apartar_Lote(Empresa, LoteId, Cliente)
        End Function
        
        Public Function Apartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Apartar_LoteAsync
            Return MyBase.Channel.Apartar_LoteAsync(Empresa, LoteId, Cliente)
        End Function
        
        Public Function Desapartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean Implements EKREST.Iwcf_enkontrol.Desapartar_Lote
            Return MyBase.Channel.Desapartar_Lote(Empresa, LoteId, Cliente)
        End Function
        
        Public Function Desapartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Desapartar_LoteAsync
            Return MyBase.Channel.Desapartar_LoteAsync(Empresa, LoteId, Cliente)
        End Function
        
        Public Function ObtenerSManzanas(ByVal Empresa As Integer, ByVal CC As String) As String Implements EKREST.Iwcf_enkontrol.ObtenerSManzanas
            Return MyBase.Channel.ObtenerSManzanas(Empresa, CC)
        End Function
        
        Public Function ObtenerSManzanasAsync(ByVal Empresa As Integer, ByVal CC As String) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerSManzanasAsync
            Return MyBase.Channel.ObtenerSManzanasAsync(Empresa, CC)
        End Function
        
        Public Function Obtener_TipoCasa(ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.Obtener_TipoCasa
            Return MyBase.Channel.Obtener_TipoCasa(Empresa)
        End Function
        
        Public Function Obtener_TipoCasaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_TipoCasaAsync
            Return MyBase.Channel.Obtener_TipoCasaAsync(Empresa)
        End Function
        
        Public Function Obtener_IdLoteXCliente(ByVal Empresa As Integer, ByVal Cliente As Integer) As Integer Implements EKREST.Iwcf_enkontrol.Obtener_IdLoteXCliente
            Return MyBase.Channel.Obtener_IdLoteXCliente(Empresa, Cliente)
        End Function
        
        Public Function Obtener_IdLoteXClienteAsync(ByVal Empresa As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Integer) Implements EKREST.Iwcf_enkontrol.Obtener_IdLoteXClienteAsync
            Return MyBase.Channel.Obtener_IdLoteXClienteAsync(Empresa, Cliente)
        End Function
        
        Public Function ObtenerUbicaciones(ByVal Empresa As Integer, ByVal Centro_Costo As String) As String Implements EKREST.Iwcf_enkontrol.ObtenerUbicaciones
            Return MyBase.Channel.ObtenerUbicaciones(Empresa, Centro_Costo)
        End Function
        
        Public Function ObtenerUbicacionesAsync(ByVal Empresa As Integer, ByVal Centro_Costo As String) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerUbicacionesAsync
            Return MyBase.Channel.ObtenerUbicacionesAsync(Empresa, Centro_Costo)
        End Function
        
        Public Function ObtenerContratos(ByVal LoteId As Integer, ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.ObtenerContratos
            Return MyBase.Channel.ObtenerContratos(LoteId, Empresa)
        End Function
        
        Public Function ObtenerContratosAsync(ByVal LoteId As Integer, ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerContratosAsync
            Return MyBase.Channel.ObtenerContratosAsync(LoteId, Empresa)
        End Function
        
        Public Function Obtener_Prototipo(ByVal Empresa As Integer, ByVal Centro_Costo As String) As String Implements EKREST.Iwcf_enkontrol.Obtener_Prototipo
            Return MyBase.Channel.Obtener_Prototipo(Empresa, Centro_Costo)
        End Function
        
        Public Function Obtener_PrototipoAsync(ByVal Empresa As Integer, ByVal Centro_Costo As String) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_PrototipoAsync
            Return MyBase.Channel.Obtener_PrototipoAsync(Empresa, Centro_Costo)
        End Function
        
        Public Function Obtener_EntregaVivienda(ByVal Empresa As Integer, ByVal Fec_Inico As Date, ByVal Fec_Fin As Date) As String Implements EKREST.Iwcf_enkontrol.Obtener_EntregaVivienda
            Return MyBase.Channel.Obtener_EntregaVivienda(Empresa, Fec_Inico, Fec_Fin)
        End Function
        
        Public Function Obtener_EntregaViviendaAsync(ByVal Empresa As Integer, ByVal Fec_Inico As Date, ByVal Fec_Fin As Date) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_EntregaViviendaAsync
            Return MyBase.Channel.Obtener_EntregaViviendaAsync(Empresa, Fec_Inico, Fec_Fin)
        End Function
        
        Public Function Obtener_Prospecciones(ByVal FechaInicio As Date, ByVal FechaFin As Date) As EKREST.Prospeccion() Implements EKREST.Iwcf_enkontrol.Obtener_Prospecciones
            Return MyBase.Channel.Obtener_Prospecciones(FechaInicio, FechaFin)
        End Function
        
        Public Function Obtener_ProspeccionesAsync(ByVal FechaInicio As Date, ByVal FechaFin As Date) As System.Threading.Tasks.Task(Of EKREST.Prospeccion()) Implements EKREST.Iwcf_enkontrol.Obtener_ProspeccionesAsync
            Return MyBase.Channel.Obtener_ProspeccionesAsync(FechaInicio, FechaFin)
        End Function
        
        Public Function Obtener_Cancelaciones(ByVal FechaInicio As Date, ByVal FechaFin As Date) As EKREST.Cancelacion() Implements EKREST.Iwcf_enkontrol.Obtener_Cancelaciones
            Return MyBase.Channel.Obtener_Cancelaciones(FechaInicio, FechaFin)
        End Function
        
        Public Function Obtener_CancelacionesAsync(ByVal FechaInicio As Date, ByVal FechaFin As Date) As System.Threading.Tasks.Task(Of EKREST.Cancelacion()) Implements EKREST.Iwcf_enkontrol.Obtener_CancelacionesAsync
            Return MyBase.Channel.Obtener_CancelacionesAsync(FechaInicio, FechaFin)
        End Function
        
        Public Function Obtener_Separaciones(ByVal FechaInicio As Date, ByVal FechaFin As Date) As EKREST.Separacion() Implements EKREST.Iwcf_enkontrol.Obtener_Separaciones
            Return MyBase.Channel.Obtener_Separaciones(FechaInicio, FechaFin)
        End Function
        
        Public Function Obtener_SeparacionesAsync(ByVal FechaInicio As Date, ByVal FechaFin As Date) As System.Threading.Tasks.Task(Of EKREST.Separacion()) Implements EKREST.Iwcf_enkontrol.Obtener_SeparacionesAsync
            Return MyBase.Channel.Obtener_SeparacionesAsync(FechaInicio, FechaFin)
        End Function
    End Class
End Namespace
