'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EKREST
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EKREST.Iwcf_enkontrol")>  _
    Public Interface Iwcf_enkontrol
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/DoWork", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/DoWork", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentesResponse")>  _
        Function ObtenerAgentes() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentes", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerAgentesResponse")>  _
        Function ObtenerAgentesAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_Agente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_AgenteResponse")>  _
        Function ObtenerDetalle_Agente(ByVal Numero_Empleado As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_Agente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerDetalle_AgenteResponse")>  _
        Function ObtenerDetalle_AgenteAsync(ByVal Numero_Empleado As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_Estatus", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_EstatusResponse")>  _
        Function Actualizar_Agente_Estatus(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_Estatus", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Actualizar_Agente_EstatusResponse")>  _
        Function Actualizar_Agente_EstatusAsync(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Insertar_Agente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Insertar_AgenteResponse")>  _
        Function Insertar_Agente(ByVal objAgenteJson As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Insertar_Agente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Insertar_AgenteResponse")>  _
        Function Insertar_AgenteAsync(ByVal objAgenteJson As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_ClienteResponse")>  _
        Function Obtener_Datos_Cliente(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_Cliente", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Obtener_Datos_ClienteResponse")>  _
        Function Obtener_Datos_ClienteAsync(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_Empresa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_EmpresaResponse")>  _
        Function ObtenerFraccionamientos_Empresa(ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_Empresa", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerFraccionamientos_EmpresaResponse")>  _
        Function ObtenerFraccionamientos_EmpresaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Apartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Apartar_LoteResponse")>  _
        Function Apartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Apartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Apartar_LoteResponse")>  _
        Function Apartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Desapartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Desapartar_LoteResponse")>  _
        Function Desapartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/Desapartar_Lote", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/Desapartar_LoteResponse")>  _
        Function Desapartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicacionesResponse")>  _
        Function ObtenerUbicaciones(ByVal Empresa As Integer, ByVal Centro_Costo As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicaciones", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerUbicacionesResponse")>  _
        Function ObtenerUbicacionesAsync(ByVal Empresa As Integer, ByVal Centro_Costo As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratos", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratosResponse")>  _
        Function ObtenerContratos(ByVal LoteId As Integer, ByVal Empresa As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratos", ReplyAction:="http://tempuri.org/Iwcf_enkontrol/ObtenerContratosResponse")>  _
        Function ObtenerContratosAsync(ByVal LoteId As Integer, ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Iwcf_enkontrolChannel
        Inherits EKREST.Iwcf_enkontrol, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Iwcf_enkontrolClient
        Inherits System.ServiceModel.ClientBase(Of EKREST.Iwcf_enkontrol)
        Implements EKREST.Iwcf_enkontrol
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements EKREST.Iwcf_enkontrol.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements EKREST.Iwcf_enkontrol.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function ObtenerAgentes() As String Implements EKREST.Iwcf_enkontrol.ObtenerAgentes
            Return MyBase.Channel.ObtenerAgentes
        End Function
        
        Public Function ObtenerAgentesAsync() As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerAgentesAsync
            Return MyBase.Channel.ObtenerAgentesAsync
        End Function
        
        Public Function ObtenerDetalle_Agente(ByVal Numero_Empleado As String) As String Implements EKREST.Iwcf_enkontrol.ObtenerDetalle_Agente
            Return MyBase.Channel.ObtenerDetalle_Agente(Numero_Empleado)
        End Function
        
        Public Function ObtenerDetalle_AgenteAsync(ByVal Numero_Empleado As String) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerDetalle_AgenteAsync
            Return MyBase.Channel.ObtenerDetalle_AgenteAsync(Numero_Empleado)
        End Function
        
        Public Function Actualizar_Agente_Estatus(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As Boolean Implements EKREST.Iwcf_enkontrol.Actualizar_Agente_Estatus
            Return MyBase.Channel.Actualizar_Agente_Estatus(Empresa, Empleado, Estatus)
        End Function
        
        Public Function Actualizar_Agente_EstatusAsync(ByVal Empresa As Integer, ByVal Empleado As String, ByVal Estatus As String) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Actualizar_Agente_EstatusAsync
            Return MyBase.Channel.Actualizar_Agente_EstatusAsync(Empresa, Empleado, Estatus)
        End Function
        
        Public Function Insertar_Agente(ByVal objAgenteJson As String) As Boolean Implements EKREST.Iwcf_enkontrol.Insertar_Agente
            Return MyBase.Channel.Insertar_Agente(objAgenteJson)
        End Function
        
        Public Function Insertar_AgenteAsync(ByVal objAgenteJson As String) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Insertar_AgenteAsync
            Return MyBase.Channel.Insertar_AgenteAsync(objAgenteJson)
        End Function
        
        Public Function Obtener_Datos_Cliente(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As String Implements EKREST.Iwcf_enkontrol.Obtener_Datos_Cliente
            Return MyBase.Channel.Obtener_Datos_Cliente(Empresa, Numero_Cliente)
        End Function
        
        Public Function Obtener_Datos_ClienteAsync(ByVal Empresa As Integer, ByVal Numero_Cliente As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.Obtener_Datos_ClienteAsync
            Return MyBase.Channel.Obtener_Datos_ClienteAsync(Empresa, Numero_Cliente)
        End Function
        
        Public Function ObtenerFraccionamientos_Empresa(ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.ObtenerFraccionamientos_Empresa
            Return MyBase.Channel.ObtenerFraccionamientos_Empresa(Empresa)
        End Function
        
        Public Function ObtenerFraccionamientos_EmpresaAsync(ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerFraccionamientos_EmpresaAsync
            Return MyBase.Channel.ObtenerFraccionamientos_EmpresaAsync(Empresa)
        End Function
        
        Public Function Apartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean Implements EKREST.Iwcf_enkontrol.Apartar_Lote
            Return MyBase.Channel.Apartar_Lote(Empresa, LoteId, Cliente)
        End Function
        
        Public Function Apartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Apartar_LoteAsync
            Return MyBase.Channel.Apartar_LoteAsync(Empresa, LoteId, Cliente)
        End Function
        
        Public Function Desapartar_Lote(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As Boolean Implements EKREST.Iwcf_enkontrol.Desapartar_Lote
            Return MyBase.Channel.Desapartar_Lote(Empresa, LoteId, Cliente)
        End Function
        
        Public Function Desapartar_LoteAsync(ByVal Empresa As Integer, ByVal LoteId As Integer, ByVal Cliente As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements EKREST.Iwcf_enkontrol.Desapartar_LoteAsync
            Return MyBase.Channel.Desapartar_LoteAsync(Empresa, LoteId, Cliente)
        End Function
        
        Public Function ObtenerUbicaciones(ByVal Empresa As Integer, ByVal Centro_Costo As String) As String Implements EKREST.Iwcf_enkontrol.ObtenerUbicaciones
            Return MyBase.Channel.ObtenerUbicaciones(Empresa, Centro_Costo)
        End Function
        
        Public Function ObtenerUbicacionesAsync(ByVal Empresa As Integer, ByVal Centro_Costo As String) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerUbicacionesAsync
            Return MyBase.Channel.ObtenerUbicacionesAsync(Empresa, Centro_Costo)
        End Function
        
        Public Function ObtenerContratos(ByVal LoteId As Integer, ByVal Empresa As Integer) As String Implements EKREST.Iwcf_enkontrol.ObtenerContratos
            Return MyBase.Channel.ObtenerContratos(LoteId, Empresa)
        End Function
        
        Public Function ObtenerContratosAsync(ByVal LoteId As Integer, ByVal Empresa As Integer) As System.Threading.Tasks.Task(Of String) Implements EKREST.Iwcf_enkontrol.ObtenerContratosAsync
            Return MyBase.Channel.ObtenerContratosAsync(LoteId, Empresa)
        End Function
    End Class
End Namespace
